# Title of the site
title: "A simple about page"
# Description of the site
description: "Example of description"

# The subpath of your site. Use "" if you're hosting a blog at the root level.
baseurl: ""
# The base hostname & protocol for your site.
url: "username.github.io"

# Articles per page
paginate: 3
# Makes pagination working
paginate_path: /projects/page:num

# Do not publish these files
exclude: ["README.md", "CHANGELOG.md", "Gemfile", "Gemfile.lock", "LICENSE"]

# Makes pretty (descriptive) permalinks.
permalink: :pretty

# Default templates
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "about"
  -
    scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"
      category: "project"
